insert into user ( username, password) values ( 'admin', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user ( username, password) values ( 'admin1',HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user ( username, password) values ( 'admin2', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user ( username, password) values ( 'gholcroft3', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'crallinshaw4', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'wbarley5', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'hdrabble6', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'mpetworth7', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'jmartelet8', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'wbegwell9', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'vgawthorpea', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'spepyeb', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'rdulyc', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'toccleshawd', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'gotuohye', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'lgouinlockf', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'apettisg', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'tkeganh', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'crodnighti', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'lcamachoj', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'fandresserk', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'mmarshfieldl', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'eoilierm', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user(username, password) values ( 'jgallicon', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'aheballo', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'cgaginp', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'ejoppichq', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'dseiner', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'thandrahans', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'kwoodyeart', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'nfiskeu', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'ncorraganv', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'fbrooksbankw', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'tmuccinox', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'ibeedelly', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'kcantrillz', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'jmaddrah10', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'kvaune11', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'tverick12', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'msieb13', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'lgillise14', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'dpedrozzi15',HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'cmockes16', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'bschneider17', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'cgledstane18', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'jtugman19', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'tbiasetti1a', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'bhayworth1b', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'ikonig1c', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (username, password) values ( 'ehake1d', HASH('SHA256', STRINGTOUTF8('test'), 1000));
