insert into user (id, username, password) values (nextval('user_seq'), 'admin', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id, username, password) values (nextval('user_seq'), 'admin1',HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id, username, password) values (nextval('user_seq'), 'admin2', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id, username, password) values (nextval('user_seq'), 'gholcroft3', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'crallinshaw4', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'wbarley5', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'hdrabble6', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'mpetworth7', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'jmartelet8', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'wbegwell9', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'vgawthorpea', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'spepyeb', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'rdulyc', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'toccleshawd', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'gotuohye', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'lgouinlockf', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'apettisg', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'tkeganh', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'crodnighti', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'lcamachoj', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'fandresserk', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'mmarshfieldl', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'eoilierm', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user(id,username, password) values (nextval('user_seq'), 'jgallicon', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'aheballo', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'cgaginp', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'ejoppichq', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'dseiner', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'thandrahans', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'kwoodyeart', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'nfiskeu', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'ncorraganv', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'fbrooksbankw', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'tmuccinox', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'ibeedelly', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'kcantrillz', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'jmaddrah10', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'kvaune11', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'tverick12', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'msieb13', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'lgillise14', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'dpedrozzi15',HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'cmockes16', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'bschneider17', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'cgledstane18', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'jtugman19', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'tbiasetti1a', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'bhayworth1b', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'ikonig1c', HASH('SHA256', STRINGTOUTF8('test'), 1000));
insert into user (id,username, password) values (nextval('user_seq'), 'ehake1d', HASH('SHA256', STRINGTOUTF8('test'), 1000));
